### ISSUE TITLE
More Fonts request

### ISSUE THREAD

**Issue by shaijyy** [patrickmollohan/c64-fonts#1]
Can you add the nytimes font? or maybe tell how to make those fonts?? and make a tutorial about how to change the font on real hardware?

**Comment by patrickmollohan** [comment]
@TEnLOcODE welcome and congrats on opening the first issue! Haha. Unfortunately, the nytimes font appears too complex to work. Essentially, each character has a space of 8px in width and height, which isn't a lot on its own, but most fonts I've created have at least a 1px empty on the bottom and left sides of the character, so it's more like 7px in width and height. As far as I can tell, most characters in the nytimes font has too much detailing to be accurately represented in 7 pixels. I have been meaning to make tutorials on all of this for a while, but ended up getting flooded with other things in life. I will certainly get something typed up for ya soon, though!

**Comment by shaijyy** [comment]
thanks, I understand that the nytimes font is too complex for the commodore64.
waiting for the tut!
